-- Migration 012: Articles d'inventaire
CREATE TABLE IF NOT EXISTS `inventory_items` (
    `id`               INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `organization_id`  INT UNSIGNED NOT NULL,
    `campaign_id`      INT UNSIGNED NOT NULL,
    `location_id`      INT UNSIGNED NOT NULL,
    `site_id`          INT UNSIGNED NOT NULL,
    `code_immo`        VARCHAR(50)  NOT NULL COMMENT 'Code immobilisation séquentiel',
    `designation`      VARCHAR(500)          DEFAULT NULL,
    `serial_number`    VARCHAR(255)          DEFAULT NULL,
    `label_roll_id`    INT UNSIGNED          DEFAULT NULL COMMENT 'Rouleau ayant fourni le code',
    `attributes`       JSON         DEFAULT NULL COMMENT 'Valeurs colonnes dynamiques',
    `photos_json`      JSON         DEFAULT NULL COMMENT '[{path, original_name, vision_label, vision_confidence}]',
    `status`           ENUM('DRAFT','VALIDATED') NOT NULL DEFAULT 'DRAFT',
    `is_duplicate_of`  INT UNSIGNED          DEFAULT NULL COMMENT 'ID de l''article original',
    `duplicate_index`  SMALLINT              DEFAULT NULL,
    `notes`            TEXT                  DEFAULT NULL,
    `imported_from`    INT UNSIGNED          DEFAULT NULL COMMENT 'import_job_id si importé',
    `created_by`       INT UNSIGNED          DEFAULT NULL,
    `updated_by`       INT UNSIGNED          DEFAULT NULL,
    `created_at`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_item_org`       (`organization_id`),
    KEY `idx_item_campaign`  (`campaign_id`),
    KEY `idx_item_location`  (`location_id`),
    KEY `idx_item_site`      (`site_id`),
    KEY `idx_item_code`      (`code_immo`),
    KEY `idx_item_roll`      (`label_roll_id`),
    KEY `idx_item_duplicate` (`is_duplicate_of`),
    CONSTRAINT `fk_item_org`      FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_item_campaign` FOREIGN KEY (`campaign_id`)     REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_item_location` FOREIGN KEY (`location_id`)     REFERENCES `locations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_item_roll`     FOREIGN KEY (`label_roll_id`)   REFERENCES `label_rolls` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_item_creator`  FOREIGN KEY (`created_by`)      REFERENCES `users` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_item_updater`  FOREIGN KEY (`updated_by`)      REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
