-- Migration 013: Anomalies
CREATE TABLE IF NOT EXISTS `anomalies` (
    `id`                  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `organization_id`     INT UNSIGNED NOT NULL,
    `campaign_id`         INT UNSIGNED NOT NULL,
    `location_id`         INT UNSIGNED          DEFAULT NULL,
    `item_id`             INT UNSIGNED          DEFAULT NULL,
    `type`                ENUM(
                              'DOUBLON_CODE',
                              'CODE_HORS_ROULEAU',
                              'FORMAT_INVALIDE',
                              'SAUT_ROULEAU',
                              'INCOHERENCE',
                              'IMAGE_DESIGNATION_MISMATCH',
                              'TYPE_CONVERSION_ERROR',
                              'CONFLIT_SYNC',
                              'CODE_HORS_SEQUENCE',
                              'MISSING_CODE'
                          ) NOT NULL,
    `status`              ENUM('OPEN','INVESTIGATION','RESOLVED','REJECTED') NOT NULL DEFAULT 'OPEN',
    `severity`            ENUM('WARNING','ERROR','BLOCKING') NOT NULL DEFAULT 'WARNING',
    `description`         TEXT                  DEFAULT NULL,
    `context_json`        JSON                  DEFAULT NULL,
    `detected_at`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `detected_by`         INT UNSIGNED          DEFAULT NULL,
    `investigated_by`     INT UNSIGNED          DEFAULT NULL,
    `investigated_at`     DATETIME              DEFAULT NULL,
    `investigation_notes` TEXT                  DEFAULT NULL,
    `resolved_by`         INT UNSIGNED          DEFAULT NULL,
    `resolved_at`         DATETIME              DEFAULT NULL,
    `resolution_notes`    TEXT                  DEFAULT NULL,
    `created_at`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_anomaly_org`      (`organization_id`),
    KEY `idx_anomaly_campaign` (`campaign_id`),
    KEY `idx_anomaly_location` (`location_id`),
    KEY `idx_anomaly_item`     (`item_id`),
    KEY `idx_anomaly_type`     (`type`),
    KEY `idx_anomaly_status`   (`status`),
    KEY `idx_anomaly_severity` (`severity`),
    CONSTRAINT `fk_anom_org`      FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_anom_campaign` FOREIGN KEY (`campaign_id`)     REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_anom_location` FOREIGN KEY (`location_id`)     REFERENCES `locations` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_anom_item`     FOREIGN KEY (`item_id`)         REFERENCES `inventory_items` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
